### PR TITLE
Compile with only 1 thread

### PR DESCRIPTION
**Pull request by bmwiedemann**
Parallel compile causes assignment of random symbol names
so we build single-threaded, which is slower, but gives reproducible results

### CODE REVIEW

**Comment by bmwiedemann** [comment]
2 example diffs without this patch:
* https://rb.zq1.de/compare.factory-20230402/diffs/xmonad-compare.out
* https://rb.zq1.de/compare.factory-20230402/diffs/texmath-compare.out

**Comment by JanZerebecki** [comment]
Filed bug at upstream: https://gitlab.haskell.org/ghc/ghc/-/issues/23299

**Comment by JanZerebecki** [comment]
Maybe picking the Debian patches or updating ghc would fix this, tests inconclusive so far, see upstream issue.

**Comment by JanZerebecki** [comment]
Ah so you already commented on an upstream bug about this a year ago and the state that they only support reproducibility with -j1 didn't change: https://gitlab.haskell.org/ghc/ghc/-/issues/12935#note_373865
I suppose there also is some -j1 buried in the Debian build scripts for this that I couldn't find.

**Review by JanZerebecki — APPROVED** [review]

**Comment by bmwiedemann** [comment]
https://github.com/opensuse-haskell/ghc-rpm-macros/commit/6b87b01d552d4b56aa1d9f6c4528343b6bc08521#diff-ba8600b0bcd187599433023cc9bd2e17d3fda6f7f06bb13fc451cc2eae72dc7bR32  broke this

**Review by peti — CHANGES_REQUESTED** [review]
Building Haskell packages with one thread only is fine for `openSUSE:Factory`, but that change would cause problems for developers who build packages locally or in the development project for maintenance and development. Those builds take very long as-is already: compiling a package like `pandoc` takes 10 minutes and more on an extremely fast multi-core machine. Running that build with only 1 thread while doing interactive development is pretty much unfeasible.

Therefore, we would need a way to switch to non-determinstic (but fast) multi-threaded builds on a per-project basis. For example, I would like to configure an attribute in OBS for https://build.opensuse.org/attribs/devel:languages:haskell that gives me fast builds, but in the absence of that attribute (e.i. in Factory) we would get slow but reproducible builds.

Would that be possible?

**Review by peti — APPROVED** [review]

**Comment by peti** [comment]
We have a problem. I applied this patch to our copy of `ghc-rpm-macros` on OBS and added the project configuration line

    %define ghc_smp_mflags %{?_smp_mflags}

to https://build.opensuse.org/projects/devel:languages:haskell:ghc-9.4.x/prjconf, which is supposed to re-enable multi-threaded builds in our devel project. However, it doesn't work. If you check any build log of any Haskell package, you'll find the build is run with

    ./Setup build -j4 -v

..., but this should be:

    ./Setup build -j4 -v

So, I dunno, re-enabling multi-threaded build doesn't seem to work as advertised. @bmwiedemann, am I missing something?

**Comment by bmwiedemann** [comment]
see https://build.opensuse.org/projects/openSUSE:ALP:Experimental:Slowroll/prjconf

You need (at the end)
```
Macros:
ghc_smp_mflags %{?_smp_mflags}
```

**Comment by peti** [comment]
Oh, yes, this looks better. Unfortunately, it still doesn't work right. Now I get this error:

~~~
[   12s] + ./Setup build -j4%_obs_cpu_flag_exclude yes -v
[   12s] invalid argument to option `-j': The jobs value should be a number or '$ncpus'
[   12s] error: Bad exit status from /var/tmp/rpm-tmp.VfXtRS (%build)
~~~

E.g. https://build.opensuse.org/package/live_build_log/devel:languages:haskell:ghc-9.4.x/ghc-OneTuple/Tumbleweed/x86_64

**Comment by bmwiedemann** [comment]
You could try instead
```
%ghc_smp_mflags -j
```

to let ghc auto-detect. This should work with the KVM builds we do in OBS, but could surprise people with chroot builds, if they wanted to use fewer cores.

**Comment by bmwiedemann** [comment]
alternatively define `%_obs_cpu_flag_exclude` as empty

**Comment by peti** [comment]
I think I figured it out. https://build.opensuse.org/projects/devel:languages:haskell:ghc-9.4.x/prjconf is set up properly now and test builds succeeded. Now I'm waiting for the project to recompile, then the new `ghc-rpm-macros` version will automatically be forwarded to Factory.

**Pull request merged**
